### ISSUE TITLE
[Epic] Automatically mark outputs of sensitive TF outputs as secrets: GA

### ISSUE THREAD

**Issue by stack72** [pulumi/pulumi-terraform-bridge#10]
This work ensures that all sensitive outputs (secrets, passwords, etc.) from Terraform-backed providers are handled as [secrets](https://www.pulumi.com/docs/intro/concepts/config/) in Pulumi.

### Work items

**Cost in engineer-weeks:** 0 remaining

#### Engineering ⚙️

* [x] Go SDK - Unsecret / IsSecret work
* [x] NodeJS SDK - unsecret / isSecret work
* [x] DotNet SDK - Unsecret / IsSecret work
* [x] Python SDK - unsecret / is_secret work
* [x] Add ability to decrypt secrets in Integration testing framework
* [x] Release pulumi/pulumi with SDK and integration testing framework changes - v2.18.0
* [x] Update the tf-bridge to return the sensitive values in TF as secrets by default
* [x] Update *all* providers with new version of TF Bridge that returns secrets\
* [x] Update provider examples with new version of the pulumi testing package

#### Launch readiness 🎁

- [x] Ship the feature
- [x] Demo the feature at TGIF
- [ ] @davidwrede: Update docs to [add a note in the Secrets conceptual material](https://pulumi.slack.com/archives/C01J4C0KVFH/p1611794529011000?thread_ts=1611789235.010700&cid=C01J4C0KVFH) after https://github.com/pulumi/docs/pull/4707 merges
- @infin8x: Blog post with broader focus on how Pulumi has secrets management built in
    - Consider competing with Tuomo on paid search

**Comment by lukehoban** [comment]
This is technically a breaking change, as it silently flows secrets into places they were previously not secret.  We should consider whether this is something that only goes into `2.0` releases.  It may be we can safely ship in 1.x once the three issues above are addressed - but calling this out to evaluate the breaking change risk before we move forward with that.

**Comment by joeduffy** [comment]
@stack72 I just ran into this and it was a bit jarring in comparison to TF's behavior (which does correctly mark things sensitive). It's too bad this missed the 2.0 release since that would have been an easy time to introduce such a change. Do we have thoughts on when we'll do this?

**Comment by stack72** [comment]
@joeduffy this was deprioritised from 2.0 - I think it's worth speaking to @lukehoban and @leezen to get this back into the priorities list

**Comment by lukehoban** [comment]
Note - we may want to consider doing https://github.com/pulumi/pulumi/issues/3795 along with this - and in fact doing https://github.com/pulumi/pulumi/issues/3795 may make it less necessary to address pulumi/pulumi#2718 or pulumi/pulumi#2993 as there would be a very easy "workaround".

**Comment by lblackstone** [comment]
https://github.com/pulumi/pulumi/pull/4956 could help with this. The pulumi schema now supports setting properties as "secret", which adds them to the `additionalSecretOutputs` resource option.

**Comment by lukehoban** [comment]
It’s become clear that this is the expected default behavior of the Pulumi secrets model, and that we should address this sooner than later. 

My suggestion is that we implement https://github.com/pulumi/pulumi/issues/3795 to ensure there is an easy “out” for any case this is not desired, and then go ahead with make this change and roll out to providers as part of minor releases.

**Comment by lukehoban** [comment]
> The three issues were (are):
> 
> * [x]  [pulumi/pulumi#2744](https://github.com/pulumi/pulumi/issues/2744)
> * [x]  [pulumi/pulumi#2718](https://github.com/pulumi/pulumi/issues/2718)
> * [ ]  [pulumi/pulumi#2993](https://github.com/pulumi/pulumi/issues/2993)
> 
> We'll need satisfactory fixes or workarounds for those before reenabling this.

FWIW - we’ve now fixed the first two, and the third is unblocked and easy to fix.

**Comment by stack72** [comment]
The rest of the work required for this Epic:

* [ ] Go SDK - Unsecret / IsSecret work
* [ ] NodeJS SDK - unsecret / isSecret work
* [ ] DotNet SDK - Unsecret / IsSecret work
* [ ] Python SDK - unsecret / is_secret work

---

* [ ] Add ability to decrypt secrets in Integration testing framework

---

* [ ] Release pulumi/pulumi with SDK and integration testing framework changes - v2.18.0

---

* [ ] Update the tf-bridge to return the sensitive values in TF as secrets by default
* [ ] Update *all* providers with new version of TF Bridge that returns secrets\
* [ ] Update provider examples with new version of the pulumi testing package

**Comment by infin8x** [comment]
#### Status week of February 1, 2021: 🟢

- On Monday, February 1, we finished releasing all providers that take advantage of this work, and updated the Epic tracker ship date to February 1 from February 2

**Comment by infin8x** [comment]
#### Status February 5, 2021: 🟢 

This work has shipped!
