### ISSUE TITLE
[Epic] Terraform Conversion Improvements

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi-terraform-bridge#1273]
## Overview

We want tf2pulumi to be a great way to migrate users from terraform to pulumi. It is currently very under-developed, can't handle many examples, has target language specific bugs, and in general could do with load of work. This epic is to track making tf2pulumi great for _most_ customer migrations, by finishing work started to support the majority of built-in TF functions, support modules, and modern TF features.

### References 📔

- [Internal channel](https://pulumi.slack.com/archives/C047FKH1N2D)

### Work Items

- [x] Publish pulumi-std
- [x] Update tf2pulumi to call functions in pulumi-std 
- [x] https://github.com/pulumi/tf2pulumi/issues/265
- [x] https://github.com/pulumi/tf2pulumi/issues/267
- [x] https://github.com/pulumi/tf2pulumi/issues/239 (started in M83)
- [x] https://github.com/pulumi/tf2pulumi/issues/186
- [ ] https://github.com/pulumi/pulumi-std/issues/17

### Convertible Examples

- [x] https://github.com/pulumi/pulumi-terraform-bridge/issues/980
- [ ] https://github.com/pulumi/pulumi-terraform-bridge/issues/945
