### ISSUE TITLE
[Epic] Switch all tfgen uses to the new converter

### ISSUE THREAD

**Issue by Frassle** [pulumi/pulumi-terraform-bridge#1280]
This epic tracks rollout of Terraform to Pulumi example converter to improve coverage and quality of examples in Registry.

https://docs.google.com/document/d/1FRQAJd17sTjfKYVhfuN9N9AtZNfRLlQv37-sIwEnDyA/edit?usp=sharing

### Work Items ⚙️

- [x] pulumi/pulumi-terraform-bridge#1352
- [x] Release bridge version with converter inside
- [x] Script comparing baseline/experimental https://github.com/pulumi/pulumi-terraform-bridge/pull/1349
- [x] https://github.com/pulumi/pulumi-terraform-bridge/issues/1413
- [x] Re-triage example quality issues and close the ones fixed
  - [x] Confirm if closed pulumi/pulumi-converter-terraform#56
  - [x] Confirm if closed pulumi/pulumi-converter-terraform#57
  - [x] Confirm if closed pulumi/pulumi-terraform-bridge#408
  - [x] TBD find more issues here
- [x] https://github.com/pulumi/ci-mgmt/issues/889
- [ ] Remove the PULUMI_CONVERT gate and commit to the new converter
- [ ] Follow up: check if conversion works on Windows, remove Windows-specific test skips
- [ ] Share a migration note with Pulumiverse and paying customers mentioning the need to pin Pulumi CLI
- [ ] Make PULUMI_CONVERT=true the default value
- [ ] Delete dead code

### Tier 2 Provider Upgrade Procedure

Since there are many of these we will use a simplified procedure. ci-mgmt will be updated to set PULUMI_CONVERT=true and ensure Pulumi CLI is pinned; then these providers will receive the improved converter during routine updates as they pull in new tfbrdige versions. Apparently there is a system in place that tracks example cov metrics  on S3, so we can monitor the process using this system.

### Associated Docs Bugs
Fixes pulumi/pulumi-terraform-bridge#1399

**Comment by t0yv0** [comment]
Please.. let's do this.

**Comment by t0yv0** [comment]
Starting to look at this. All the meaningful changes are scoped to tf2pulumi package. It turns out
tfgen package depends on tf2pulumi package through a fairly small set of APIs.
  
Option 1:

- add interfaces between tfgen and tf2pulumi
- move tf2pulumi to tfpulumilegacy implementing the interfaces
- merge gh:pulumi/pulumi-terraform-bridge#677 to be the new "tf2pulumi", implementing the intefaces
- provide a switch in ProviderInfo to decide which converter we use
- upgrade providers one by one to the new converter

Option 2:

- merge gh:pulumi/pulumi-terraform-bridge#677 as is to master
- release new tfbridge
- providers that get the new tfbridge land the new converter

Option 2 is less work the only downside is that it is a hard commit, so providers can either get the
new converter plus pending bridge fixes or neither and cannot pick and choose.

Before deciding which way to go I'm going to run a quick experiment to look at example conversion
stats on the new converter vs stauts quo on tier 1 providers. If as we expect the changes are
primarily beneficial that adds weight to going with the lighter Option 1.

**Comment by t0yv0** [comment]
Hrm. Noticing that the new code has PULUMI_EXPERIMENTAL gate. Testing GCP:

```
BASELINE

General metrics:
        784 total resources containing 9722 total inputs.
        248 total functions.
        0 entities are missing docs entirely because they could not be found in the upstream provider.

Description metrics:
        49 entity descriptions contained an <elided> reference and were dropped, including examples.
        60 entity descriptions contained an <elided> reference and were dropped, but examples were preserved.

Example conversion metrics:
        72 HCL examples failed to convert in all languages
        93 HCL examples were converted in at least one language but failed to convert to TypeScript
        93 HCL examples were converted in at least one language but failed to convert to Python
        94 HCL examples were converted in at least one language but failed to convert to Go
        93 HCL examples were converted in at least one language but failed to convert to C#
        971 entity document sections contained unexpected HCL code snippets. Examples will be converted, but may not display correctly in the registry, e.g. lacking tabs.

Argument metrics:
        5259 argument descriptions were parsed from the upstream docs
        14 top-level input property descriptions came from an upstream attribute (as opposed to an argument). Nested arguments are not included in this count.
        80 arguments contained an <elided> reference and had their descriptions dropped.
        44 nested arguments contained an <elided> reference and had their descriptions dropped.
        1209 of 9722 resource inputs (12.44%) are missing descriptions in the schema

Attribute metrics:
        12 attributes contained an <elided> reference and had their descriptions dropped.


NEW CODE

Description metrics:
        49 entity descriptions contained an <elided> reference and were dropped, including examples.
        60 entity descriptions contained an <elided> reference and were dropped, but examples were preserved.

Example conversion metrics:
        72 HCL examples failed to convert in all languages
        93 HCL examples were converted in at least one language but failed to convert to TypeScript
        93 HCL examples were converted in at least one language but failed to convert to Python
        94 HCL examples were converted in at least one language but failed to convert to Go
        93 HCL examples were converted in at least one language but failed to convert to C#
        971 entity document sections contained unexpected HCL code snippets. Examples will be converted, but may not display correctly in the registry, e.g. lacking tabs.

Argument metrics:
        5259 argument descriptions were parsed from the upstream docs
        14 top-level input property descriptions came from an upstream attribute (as opposed to an argument). Nested arguments are not included in this count.
        80 arguments contained an <elided> reference and had their descriptions dropped.
        44 nested arguments contained an <elided> reference and had their descriptions dropped.
        1209 of 9722 resource inputs (12.44%) are missing descriptions in the schema

Attribute metrics:
        12 attributes contained an <elided> reference and had their descriptions dropped.


NEW CODE + EXPERIMENTAL

Example conversion metrics:
        77 HCL examples failed to convert in all languages
        5 HCL examples were converted in at least one language but failed to convert to TypeScript
        5 HCL examples were converted in at least one language but failed to convert to Python
        6 HCL examples were converted in at least one language but failed to convert to Go
        5 HCL examples were converted in at least one language but failed to convert to C#
        971 entity document sections contained unexpected HCL code snippets. Examples will be converted, but may not display correctly in the registry, e.g. lacking tabs.

Argument metrics:
        5259 argument descriptions were parsed from the upstream docs
        14 top-level input property descriptions came from an upstream attribute (as opposed to an argument). Nested arguments are not included in this count.
        80 arguments contained an <elided> reference and had their descriptions dropped.
        44 nested arguments contained an <elided> reference and had their descriptions dropped.
        1209 of 9722 resource inputs (12.44%) are missing descriptions in the schema

Attribute metrics:
        12 attributes contained an <elided> reference and had their descriptions dropped.

```

**Comment by t0yv0** [comment]
So we can simplify rollout plan I think, updating.

**Comment by t0yv0** [comment]
@cnunciato kindly agreed to help out making provider registry builds to help validate the Tier 1 PRs. But unfortunately since that conversation I started rebasing the PRs and hit a new blocker. https://github.com/pulumi/pulumi/issues/14718 I believe Fraser is looking at this presently.

**Comment by t0yv0** [comment]
Blocked on https://github.com/pulumi/pulumi-yaml/issues/539

**Comment by t0yv0** [comment]
This just shipped so we should be unblocked! Wonderful news.

**Comment by Frassle** [comment]
> This just shipped so we should be unblocked! 

It merged, we need to do a yaml and pulumi release still.

**Comment by t0yv0** [comment]
Almost there, next pulumi release I can finish this off for the Tier1 providers at least I believe.

**Comment by t0yv0** [comment]
Another round of iteration, Fraser unblocked another problem (🙇 ), the latest version of the converter gives non-deterministic build results again, digging into that tomorrow. That seems like the last known blocker-level problem for rolling out to tier1.

**Comment by t0yv0** [comment]
https://github.com/pulumi/pulumi-azure/pull/1377 PR is in the best shape of how this looks like (latest version).

**Comment by t0yv0** [comment]
Exploring cleanup in https://github.com/pulumi/pulumi-terraform-bridge/pull/2004

**Comment by t0yv0** [comment]
Wrote comms https://github.com/pulumi/pulumi-terraform-bridge/issues/2037 we should circulate and get feedback on before pulling the trigger.

**Comment by t0yv0** [comment]
Per conversation with @mjeffryes , closing as completed and tracking comms+cleanup in a new epic https://github.com/pulumi/home/issues/3452
