### ISSUE TITLE
[Tracking Issue] Misformatted API Docs

### ISSUE THREAD

**Issue by iwahbe** [pulumi/pulumi-terraform-bridge#1291]
Here we list issues where the terraform docs where correctly formatted but the pulumi docs are not correctly formatted.

```[tasklist]
- [ ] https://github.com/pulumi/pulumi-aws/issues/2427
- [ ] https://github.com/pulumi/pulumi-signalfx/issues/377
- [ ] https://github.com/pulumi/pulumi-mongodbatlas/issues/165
- [ ] https://github.com/pulumi/pulumi-terraform-bridge/issues/351
- [ ] https://github.com/pulumi/pulumi-terraform-bridge/issues/926
- [ ] https://github.com/pulumi/pulumi-terraform-bridge/issues/847
- [ ] https://github.com/pulumi/pulumi-terraform-bridge/issues/553
- [ ] https://github.com/pulumi/pulumi-aws/issues/2624
- [ ] https://github.com/pulumi/pulumi-terraform-bridge/issues/1344
- [ ] https://github.com/pulumi/pulumi-terraform-bridge/issues/1530
- [ ] https://github.com/pulumi/pulumi-gcp/issues/1375
- [ ] https://github.com/pulumi/pulumi-aws/issues/3100
- [ ] https://github.com/pulumi/pulumi-gcp/issues/1895
- [ ] https://github.com/pulumi/pulumi-gcp/issues/1920
```

**Comment by guineveresaenger** [comment]
Tracking these in https://github.com/pulumi/pulumi-terraform-bridge/issues/1795#issuecomment-2070772865 and #1794 going forward.
