### ISSUE TITLE
[Tracking Issue] Incorrect API Docs

### ISSUE THREAD

**Issue by iwahbe** [pulumi/pulumi-terraform-bridge#1292]
Here we list items where the terraform docs are accurate but the pulumi docs are no longer accurate.

- [ ] https://github.com/pulumi/pulumi-aws/issues/1620
- [ ] https://github.com/pulumi/pulumi-terraform-bridge/issues/807
- [ ] https://github.com/pulumi/pulumi-terraform-bridge/issues/531
- [ ] https://github.com/pulumi/pulumi-terraform-bridge/issues/1358
- [x] https://github.com/pulumi/pulumi-cloudflare/issues/661
- [ ] https://github.com/pulumi/pulumi-gcp/issues/1879
- [x] https://github.com/pulumi/pulumi-cloudflare/issues/700

**Comment by guineveresaenger** [comment]
Tracking these in https://github.com/pulumi/pulumi-terraform-bridge/issues/1795#issuecomment-2070772865 and #1794 going forward.
