### ISSUE TITLE
Rollout experimental converter to Tier 1 providers

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-terraform-bridge#1413]
By provider:

- [x] aws https://github.com/pulumi/pulumi-aws/pull/2882
- [x] gcp https://github.com/pulumi/pulumi-gcp/pull/1266
- [x] azure https://github.com/pulumi/pulumi-azure/pull/1377
- [x] azuread https://github.com/pulumi/pulumi-azuread/pull/484

*Tier 1 Provider Upgrade Procedure*:

- Apply https://github.com/pulumi/ci-mgmt/pull/655 workflows
- Flip pulumiConvert to 1 in .ci-mgmt.yaml
- Run `make ci-mgmt`
- Upgrade bridge dependency to the supported version including https://github.com/pulumi/pulumi-terraform-bridge/pull/1401
- Run `make tfgen provider build_sdks` and commit
- Run a script to compute before/after metrics https://github.com/pulumi/pulumi-terraform-bridge/pull/1349
- Stand up a PR showcasing the script output
- If any examples regressed, analyze and open tickets; use COVERAGE_OUTPUT_DIR="$PWD/cov" to get details
- If no examples regressed or regressions are immaterial, merge the PR
- Release the updated provider

Example output for pulumi-gcp:

```
Baseline     2328
Provider:     google-beta
Success rate: 95.16% (13144/13812)

Converted 93.96% of csharp examples (2163/2302)
Converted 93.92% of go examples (2162/2302)
Converted 97.87% of java examples (2253/2302)
Converted 93.96% of python examples (2163/2302)
Converted 93.96% of typescript examples (2163/2302)
Converted 97.31% of yaml examples (2240/2302)

Experimental 2328
Provider:     google-beta
Success rate: 99.69% (13464/13506)

Converted 99.78% of csharp examples (2246/2251)
Converted 99.73% of go examples (2245/2251)
Converted 99.60% of java examples (2242/2251)
Converted 99.78% of python examples (2246/2251)
Converted 99.78% of typescript examples (2246/2251)
Converted 99.47% of yaml examples (2239/2251)
```

**Comment by t0yv0** [comment]
Merges blocked per conversation with the docs team. Reminder to look at it on 19th.

**Comment by t0yv0** [comment]
A bit more progress here. We landed 14718 thanks to the platform team so the pipeline is now working in a stable fashion. However, further analysis of the Azure AD PR uncovered regressions in example quality:

https://github.com/pulumi/pulumi-converter-terraform/issues/89
https://github.com/pulumi/pulumi-converter-terraform/issues/88

The YAML one is particularly egregious and I would consider a blocker again.

**Comment by t0yv0** [comment]
Many thanks to @Frassle and @Zaid-Ajaj working through some build stability issues in the converter; this is now rolled out to the above providers.
