### ISSUE TITLE
[Epic] API Docs Q3/Q4 Improvements

### ISSUE THREAD

**Issue by iwahbe** [pulumi/pulumi-terraform-bridge#1637]
This is the Team Provider Infra version of https://github.com/pulumi/registry/issues/3780.

```[tasklist]
### Q3
- [ ] Begin measuring and publishing example-conversion metrics
- [ ] Begin measuring and publishing content ingestion quality, including imports
- [ ] Identify and incorporate any existing high-value issues related to docs content quality
- [ ] https://github.com/pulumi/pulumi-terraform-bridge/issues/1280
- [ ] Indicate alongside examples whether they compile and/or preview successfully
- [ ] Enable documentation of provider overlays
- [x] P2: Customer Request: https://github.com/pulumi/pulumi-terraform-bridge/issues/1045
```

```[tasklist]
### Q4
- [ ] Providers: Pull examples and resource imports content out of the `description` field (blocked by `Extend schema to allow dedicated "examples" and "import" sections` above)

```

**Comment by cnunciato** [comment]
Hey @iwahbe, do we need this second issue here, or can we just use the epic? I'd prefer we had one if we could, just for clarity and to have a single source of truth.

**Comment by mjeffryes** [comment]
Closing incomplete for Q3; continuing work in https://github.com/pulumi/pulumi-terraform-bridge/issues/1794
