### ISSUE TITLE
[EPIC] Rollout PlanResourceChange

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-terraform-bridge#1785]
🚧 

PlanResourceChange flag enables a rewritten implementation of the lifecycle for SDKv2 based resources that more closely aligns with how TF CLI exercises the providers. Building out a plan to roll it out as the default behavior in the bridge. Currently it is rolled out selectively on a per-resource basis where it is shown to fix significant issues.

- Introduce initial version in https://github.com/pulumi/pulumi-terraform-bridge/pull/1614
- pulumi/pulumi-aws#1504
- pulumi/pulumi-aws#2555
- pulumi/pulumi-aws#3359
- https://github.com/pulumi/pulumi-terraform-bridge/issues/1822
- https://github.com/pulumi/pulumi-terraform-bridge/issues/1791 (verify that discrepancies here are non-critical)
- https://github.com/pulumi/pulumi-terraform-bridge/issues/1827
- https://github.com/pulumi/pulumi-terraform-bridge/issues/2034
- ~https://github.com/pulumi/pulumi-terraform-bridge/issues/2039~ (not a PRC issue, fixed in https://github.com/pulumi/pulumi-terraform-bridge/pull/2081)
- https://github.com/pulumi/pulumi-terraform-bridge/issues/1962
- https://github.com/pulumi/pulumi-terraform-bridge/issues/1967 (will be closed with https://github.com/pulumi/pulumi-terraform-bridge/pull/2065)
- https://github.com/pulumi/pulumi-terraform-bridge/issues/2047 (will be closed with https://github.com/pulumi/pulumi-terraform-bridge/pull/2065)
- ~https://github.com/pulumi/pulumi-gcp/issues/2078~ (issue in GCP tests, fixed in https://github.com/pulumi/pulumi-gcp/pull/2072)
- https://github.com/pulumi/pulumi-terraform-bridge/issues/2284

## Technicalities

What PlanResourceChange flag does: it currently is a partial rewrite of the resource lifecycle methods for bridging the SDKv2-based resources. It ties into as much as possible into TF gRPC implementations to work "exactly-as" TF. Several known areas where this improves things:

- RawState, RawConfig and RawPlan are computed as-in TF; when they differ this may lead to panics in providers
- Does not call CustomizeDiff repeatedly, matching TF behavior more closely and solving complicated bugs

Cross-testing is essential to pin down corner cases and get full confidence before broader rollout.

## Rollout

We will start the rollout as follows:
 - [x] random
 - [x] cloudflare
 - [x] The rest of tier 2
 - [x] GCP and Azure
 - [x] AWS
 - [ ] Cleanup

### Instances of TF behaviour regressing against non-PRC:
 - https://github.com/pulumi/pulumi-gcp/issues/2083

**Comment by VenelinMartinov** [comment]
https://github.com/pulumi/pulumi-terraform-bridge/issues/1822 is likely the GCP Meta handling issue.

**Comment by t0yv0** [comment]
Some updates. There's still some very basic issues around unknown handling (https://github.com/pulumi/pulumi-terraform-bridge/issues/1943) causing customer P1s in AWS (https://github.com/pulumi/pulumi-aws/commit/8c302b9355882df9d70bfff6eb2d5a09bb386862) for resources where this was speculatively rolled out to fix other P1s or diff issues like in the case of LaunchTemplate.

Given this situation, after https://github.com/pulumi/pulumi-terraform-bridge/issues/1943 it would be great to open a bridge PR that runs all the downstream tests with this feature turned on to see if we can spot any more basic simple failures and proactively fix them.

The issue in question could have been located by https://github.com/pulumi/pulumi-terraform-bridge/issues/1858 but I would bet also regular integration tests would flag it somewhere.

**Comment by t0yv0** [comment]
ON a positive note we landed https://github.com/pulumi/pulumi-terraform-bridge/pull/1927 which together with this flag is shown to close 4 resource cycling issues in AWS, and likely actually fixes a lot more.

**Comment by VenelinMartinov** [comment]
We could add an env var which default enables this perhaps?

Then run downstream tests with the env var enabled

**Comment by t0yv0** [comment]
Exactly. The issues from actual integration tests likely cover the most important basics.

**Comment by VenelinMartinov** [comment]
Should we finish https://github.com/pulumi/pulumi-terraform-bridge/issues/1858 and maybe https://github.com/pulumi/pulumi-terraform-bridge/issues/1864 before rolling this out?

**Comment by t0yv0** [comment]
As discussed today:

- Include https://github.com/pulumi/pulumi-terraform-bridge/issues/1964 panic as requirement for release
- https://github.com/pulumi/pulumi-terraform-bridge/pull/1971 is borderline but we wanted to include it as requirement
- do not include https://github.com/pulumi/pulumi-terraform-bridge/issues/1791 as requirement for release
- similarly do not include 1858 and 1864 as requirements

For failing downstream checks do not over-index on upgrade tests flagging Updates, this is not unexpected and we can weaken the tests to just weed out replacements.

**Comment by VenelinMartinov** [comment]
https://github.com/pulumi/pulumi-terraform-bridge/issues/2039 reproes on non-PRC, removing it from the list.

**Comment by VenelinMartinov** [comment]
https://github.com/pulumi/pulumi-gcp/issues/2078 is actually an upstream bug/behaviour uncovered by PRC

**Comment by VenelinMartinov** [comment]
1967 and 2047 are addressed by https://github.com/pulumi/pulumi-terraform-bridge/pull/2065 so we only need to run down all the failures in https://github.com/pulumi/pulumi-terraform-bridge/issues/1962

**Comment by VenelinMartinov** [comment]
We should be good to go here - will enable PRC in pulumi-random with the new bridge release.

**Comment by VenelinMartinov** [comment]
pulumi-random is entirely PF based, so we can't start the rollout there.

Opened https://github.com/pulumi/pulumi-cloudflare/pull/828 for pulumi-cloudflare

**Comment by t0yv0** [comment]
Any updates on the tier 2 rollout, anything I can help with?

**Comment by VenelinMartinov** [comment]
Thanks, last week was a bit short-handed so I didn't manage to do the rollout. Doing it today:

- [X] https://github.com/pulumi/pulumi-cloudflare
- [ ] https://github.com/pulumi/pulumi-datadog
- [ ] https://github.com/pulumi/pulumi-digitalocean
- [ ] https://github.com/pulumi/pulumi-github
- [ ] https://github.com/pulumi/pulumi-mongodbatlas
- [ ] ~https://github.com/pulumi/pulumi-random~ (PF only)
- [ ] https://github.com/pulumi/pulumi-tls
- [ ] https://github.com/pulumi/pulumi-auth0
- [ ] https://github.com/pulumi/pulumi-postgresql

**Comment by VenelinMartinov** [comment]
Tier 2 rollout completed, will continue with GCP and Azure around 30th of July.

**Comment by VenelinMartinov** [comment]
I believe we agreed on 14d - https://github.com/pulumi/pulumi-terraform-bridge/issues/1785#issuecomment-2188731242 was posted on the 25th of June and scheduled the next step for the 9th of July. (14 days between)

Maybe we can make a case for accelerating given that we've seen to downsides so far.

**Comment by VenelinMartinov** [comment]
We've also fixed 1 more panic and 5 more permadiffs with PRC:
 - https://github.com/pulumi/pulumi-gcp/pull/2165
 - https://github.com/pulumi/pulumi-gcp/pull/2174
 - https://github.com/pulumi/pulumi-gcp/pull/2182
 - https://github.com/pulumi/pulumi-azure/pull/2150
 - https://github.com/pulumi/pulumi-gcp/pull/2114
 - https://github.com/pulumi/pulumi-confluentcloud/pull/517

**Comment by t0yv0** [comment]
Allright, I might be mis-remembering. Happy to stick to the plan, there's a few things pending in AWS awaiting this change but nothing urgent yet.

**Comment by VenelinMartinov** [comment]
Both GCP and Azure have test failures when attempting to enable PRC by default, will need to be revisited:
https://github.com/pulumi/pulumi-azure/pull/2306
https://github.com/pulumi/pulumi-gcp/pull/2277

**Comment by VenelinMartinov** [comment]
Adding https://github.com/pulumi/pulumi-terraform-bridge/issues/2284

**Comment by VenelinMartinov** [comment]
PRC was enabled by default in GCP in https://github.com/pulumi/pulumi-gcp/releases/tag/v7.36.0

**Comment by VenelinMartinov** [comment]
Debugging the Azure PRC failures in https://github.com/pulumi/pulumi-azure/issues/2322

The first one is a replacement on a basic resource which reproes in TF under -refresh=false = (
https://github.com/pulumi/pulumi-azure/issues/2323

**Comment by t0yv0** [comment]
Can we consider a resource-specific workaround for this?

**Comment by VenelinMartinov** [comment]
Yeah, I have one in https://github.com/pulumi/pulumi-azure/pull/2325

**Comment by VenelinMartinov** [comment]
The last Azure test which is failing is due to https://github.com/pulumi/pulumi-terraform-bridge/issues/2293
https://github.com/pulumi/pulumi-azure/issues/2322#issuecomment-2297073944

**Comment by VenelinMartinov** [comment]
Azure is done: https://github.com/pulumi/pulumi-azure/pull/2306

**Comment by VenelinMartinov** [comment]
Investigating PRC test failures in AWS here: https://github.com/pulumi/pulumi-aws/issues/4410

**Comment by VenelinMartinov** [comment]
Started on the bridge cleanup https://github.com/pulumi/pulumi-terraform-bridge/pull/2380 so that we can base other work off of that.

**Comment by VenelinMartinov** [comment]
Possible issue with user-defined timeout overrides for Create under PRC: https://github.com/pulumi/pulumi-terraform-bridge/issues/2386

**Comment by t0yv0** [comment]
Progress this week on fixing the emergent custom timeouts issue 2386; next up: roll out to AWS, cleanup and close. AWS rollout delayed as waiting for a bridge release to pass all downstream tests.

**Comment by t0yv0** [comment]
https://github.com/pulumi/pulumi-aws/issues/4457 is a consequence we believe, but it is quite tricky. The low-level behavior is more inline with matching TF (our goal) but at the higher level we have gaps to make the users be able to get unstuck.

**Comment by t0yv0** [comment]
https://github.com/pulumi/pulumi-gcp/issues/2372 is this a consequence of PRC rollout?

**Comment by mjeffryes** [comment]
Yes, the behavior is actually more consistent with the upstream behavior with PRC, but this results in unexpected diffs for when there are labels set as ""

**Comment by VenelinMartinov** [comment]
Another persistent diff fixed by PRC: https://github.com/pulumi/pulumi-newrelic/issues/875

**Comment by t0yv0** [comment]
One more fix possibly: https://github.com/pulumi/pulumi-aws/issues/1784 per @corymhall

**Comment by VenelinMartinov** [comment]
New issue with detailed diff when a set contains an unknown element: https://github.com/pulumi/pulumi-terraform-bridge/issues/2427

**Comment by VenelinMartinov** [comment]
possibly fixed with this: https://github.com/pulumi/pulumi-azuread/issues/1338
