### ISSUE TITLE
Finish High-value Bridge Docs Fixes

### ISSUE THREAD

**Issue by mjeffryes** [pulumi/pulumi-terraform-bridge#1794]
There are a few remaining high impact improvements we'd like to make to the docs generated by the bridge: 

```[tasklist]
### Tasks
- [ ] https://github.com/pulumi/pulumi-terraform-bridge/issues/1789
- [ ] https://github.com/pulumi/registry/issues/4749
- [ ] https://github.com/pulumi/pulumi-terraform-bridge/issues/1280
- [ ] https://github.com/pulumi/pulumi-terraform-bridge/issues/1795
- [ ] https://github.com/pulumi/pulumi-terraform-bridge/issues/1774
- [ ] https://github.com/pulumi/pulumi-aws/issues/1620
- [ ] https://github.com/pulumi/pulumi-terraform-bridge/issues/531
- [ ] https://github.com/pulumi/pulumi-libvirt/issues/335
- [ ] https://github.com/pulumi/pulumi-gcp/issues/1879
- [ ] https://github.com/pulumi/pulumi-mongodbatlas/issues/165
- [ ] https://github.com/pulumi/pulumi-spotinst/issues/366
- [ ] https://github.com/pulumi/pulumi-terraform-bridge/issues/530
- [ ] https://github.com/pulumi/pulumi-kafka/issues/199
- [ ] https://github.com/pulumi/pulumi-terraform-bridge/issues/1547
- [ ] https://github.com/pulumi/pulumi-terraform-bridge/issues/1507
- [ ] https://github.com/pulumi/pulumi-signalfx/issues/377
```

**Comment by t0yv0** [comment]
Do you want me to take on #1280 next iteration? It's just 3d of tedium, not unreasonable to impose on me for reasons of familiarity.
