### ISSUE TITLE
Cross-testing (aka conformance testing) goals for Q4

### ISSUE THREAD

**Issue by mjeffryes** [pulumi/pulumi-terraform-bridge#1796]
```[tasklist]
### Tasks
- [ ] https://github.com/pulumi/pulumi-terraform-bridge/issues/1790
- [ ] https://github.com/pulumi/pulumi-terraform-bridge/issues/1791
- [ ] https://github.com/pulumi/pulumi-terraform-bridge/issues/1785
- [ ] https://github.com/pulumi/pulumi-terraform-bridge/issues/1792
- [ ] https://github.com/pulumi/pulumi-terraform-bridge/issues/1736
- [ ] https://github.com/pulumi/pulumi-terraform-bridge/issues/1763
```
