### ISSUE TITLE
[Epic] Maintain and generate provider installation instructions in-provider

### ISSUE THREAD

**Issue by guineveresaenger** [pulumi/pulumi-terraform-bridge#2083]
This effort has two major parts:

1. Keep `installation_configuration.md` and `index.md` files in-provider. As of today this is mainly a migration from pulumi/registry to $provider/docs.

2. Consume upstream upstream `index.md` file to $provider/docs
  a) Transform the content to match Pulumi standards.

- [x] https://github.com/pulumi/registry/issues/4740
- [x] https://github.com/pulumi/pulumi-terraform-bridge/issues/2082
- [x] https://github.com/pulumi/pulumi-terraform-bridge/issues/2078 (this is a tracking issue with a checklist of necessary transformations).

**Comment by guineveresaenger** [comment]
Update, 9/30:

During the [rollout](https://github.com/pulumi/home/issues/3598), we gathered important information on exactly which transformations different providers will need for this landing page to build well and be usable.

Overall, it's been a bit slower to roll out, because there are so many potentially different situations presenting in upstream docs - but the good news is that for the most part, these situations can be generalized and applied globally in the bridge.

The following themes were discovered and implemented in addition to the sub-issues in https://github.com/pulumi/pulumi-terraform-bridge/issues/2078:

- Translation and display of the Pulumi.yaml file to show config examples 
    - https://github.com/pulumi/pulumi-terraform-bridge/pull/2214
- Docs edits transforming TF verbiage to Pulumi language 
    - https://github.com/pulumi/pulumi-terraform-bridge/pull/2350
    - https://github.com/pulumi/pulumi-terraform-bridge/pull/2421
    - https://github.com/pulumi/pulumi-terraform-bridge/pull/2431
- Ordering of docs edits 
    - https://github.com/pulumi/pulumi-terraform-bridge/pull/2435
- Addition of an end-to-end docs transformation test for the bridge
    - https://github.com/pulumi/pulumi-terraform-bridge/pull/2435
- Moving toward AST based Markdown parsing 
    - https://github.com/pulumi/pulumi-terraform-bridge/pull/2361
    - https://github.com/pulumi/pulumi-terraform-bridge/pull/2292
- Multiple small docs edits to smooth along the process for providers more globally
    - https://github.com/pulumi/pulumi-terraform-bridge/pull/2435
    - https://github.com/pulumi/pulumi-terraform-bridge/pull/2421
    - https://github.com/pulumi/pulumi-terraform-bridge/pull/2350
    - https://github.com/pulumi/pulumi-terraform-bridge/pull/2342
    - https://github.com/pulumi/pulumi-terraform-bridge/pull/2344
- Strip TF version references 
    - https://github.com/pulumi/pulumi-terraform-bridge/pull/2349
- The section skipping functionality is implemented as an exported docsEdit function that providers can use for one-off section skipping.
- All new work is under test, and missing tests were implemented for some of the existing functionality.
- We have rolled out 2/3 of lower-tier providers, and believe most of the remainder of the rollout will be simplified by the work listed in this comment.

We also encountered a few challenges with our Markdown renderer:
- https://github.com/pulumi/pulumi-terraform-bridge/issues/2420
- https://github.com/pulumi/pulumi-terraform-bridge/pull/2335
- https://github.com/pulumi/pulumi-terraform-bridge/pull/2306

Overall, the outcome here is optimistic for future streamlining of docs transformations, making automation more robust and usable. The things we learned may ultimately benefit the registry docs in general as well -see https://github.com/pulumi/pulumi-terraform-bridge/issues/2251 and https://github.com/pulumi/pulumi-terraform-bridge/issues/2248.

**Comment by guineveresaenger** [comment]
This issue is complete.
