### ISSUE TITLE
[Plugin Framework] Ensure that ProviderInfo customizations work properly or generate warnings

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-terraform-bridge#828]
The architecture of the Plugin Framework version of the bridge reuses some but not all of the previous code, resulting in some confusion around the configuration/mapping options. Both old and new providers accept this structure with a lot of custom options:

- [ProviderInfo](https://github.com/pulumi/pulumi-terraform-bridge/blob/master/pkg/tfbridge/info.go#L47-#L47)

The options released to tweaking schema generation work already because the same underlying code is used. The runtime options do not. Specifically:

- [x] SchemaInfo works partially
   - [x] Name customizations work as well as MaxItems=1
   - [x] Setting Default warns, backlogged https://github.com/pulumi/pulumi-terraform-bridge/issues/938
   - [x] Secret option appears to only mark the prop as Secret in Pulumi Package Schema and not enforce any runtime work
   - [x] Setting Removed now warns; it appears that in sdk-v2 at runtime v2schema.Removed() is always "" so is is not in use at runtime; we can consider deprecating or wait for any user requests about it
   - [x] MarkAsComputedOnly, MarkAsOptional seem to be tfgen-level features, no need to warn on those
   - [x] Stable, ForceNew generates warnings, backlogged feature: https://github.com/pulumi/pulumi-terraform-bridge/issues/936
   - [x] AssetTranslation - warnings installed, support required in https://github.com/pulumi/pulumi-terraform-bridge/issues/750 
   - [x] Transform - warnings installed, support backlogged https://github.com/pulumi/pulumi-terraform-bridge/issues/937
- [x] ResourceInfo
  - [x] DeleteBeforeReplace is ignored - actually turns out it is not ignored, https://github.com/pulumi/pulumi-terraform-bridge/pull/934 do not warn on it
  - [x] UniqueNamedFields is ignored - https://github.com/pulumi/pulumi-terraform-bridge/issues/931 backlog support, very rarely used feature; now we warn if it's populated in TFPF
  - [x] IDFields - deprecate https://github.com/pulumi/pulumi-terraform-bridge/pull/933
- [x] PreConfigureCallback, PreConfigureCallbackWithLogger - emit warnings now, backlog support in https://github.com/pulumi/pulumi-terraform-bridge/issues/935
- [x] ExtraTypes, ExtraResources, ExtraFunctions, ExtraConfig - assumed to work, elide warnings in https://github.com/pulumi/pulumi-terraform-bridge/pull/932

**Comment by t0yv0** [comment]
#881
