### ISSUE TITLE
[Epic] Q2 Bridge Quality

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-terraform-bridge#886]
[Internal Design Doc](https://docs.google.com/document/d/1wL5CgLyi0FKuyrRzf56umTMcXxMkbH8BZWHwhNt4_-k/edit?usp=sharing)

Timeline: Q2

- [x] Scan kind/bug issues in pulumi-terraform-bridge, adopt some of them in the epic
- [x] #343 
- [x] https://github.com/pulumi/pulumi-terraform-bridge/issues/906
- [x] panic #570 
- [x] panic #940
- [x] #923
- [x] https://github.com/pulumi/pulumi-terraform-bridge/issues/651
- [x] Scan bridged Tier 1 providers for issues that might belong here
    - Schedule calls with interested parties (@kpitzen interested)
    - Place to start https://metabase.corp.pulumi.com/question/1717-top-issues-tier-1-providers
    - Also ditto Airtable
    - Quite possibly issue we find there pre-empt the list below
- [3] https://github.com/pulumi/pulumi-aws/issues/1423
- [1] https://github.com/pulumi/pulumi-random/issues/286
- [3] #244
- [3] https://github.com/pulumi/pulumi-terraform-bridge/issues/352
- [2] https://github.com/pulumi/pulumi-terraform-bridge/issues/493
- [1] https://github.com/pulumi/pulumi-terraform-bridge/issues/496
- [1] https://github.com/pulumi/pulumi-terraform-bridge/issues/607
- [1] https://github.com/pulumi/pulumi-terraform-bridge/issues/62
- [1] https://github.com/pulumi/pulumi-terraform-bridge/issues/6
- [1] #97 
- [1] https://github.com/pulumi/pulumi-terraform-bridge/issues/528
- [1] #635 try to repro likely closed 
- [1] #335 try to repro likely closed

To triage:
- https://github.com/pulumi/pulumi-terraform-bridge/issues/1048

**Comment by iwahbe** [comment]
For testing, should we add these?
- https://github.com/pulumi/pulumi-terraform-bridge/issues/898
- https://github.com/pulumi/pulumi-terraform-bridge/issues/877 (might be addressed soon)

**Comment by iwahbe** [comment]
We have agreed to address https://github.com/pulumi/pulumi-cloudflare/issues/366 as part of bridge work in Q2. @t0yv0 can I add it to the epic.

This works in TF, so the problem is the bridge treating empty objects differently then TF.

**Comment by AaronFriel** [comment]
Another candidate issue: https://github.com/pulumi/pulumi-random/issues/286

**Comment by t0yv0** [comment]
I've missed https://github.com/pulumi/pulumi-terraform-bridge/issues/723 because I was scanning mostly bugs. I feel like it can fit here with #651 same area.

**Comment by iuliancristea** [comment]
Hi @t0yv0 - For https://github.com/pulumi/pulumi-terraform-bridge/issues/635, the issue is very much still there and causing problems.

**Comment by t0yv0** [comment]
Relevant label: https://github.com/pulumi/pulumi-aws/issues?q=is%3Aissue+is%3Aopen+label%3Abug%2Fdiff+

**Comment by phillipedwards** [comment]
@t0yv0 just curious, is there any timeline for https://github.com/pulumi/pulumi-terraform-bridge/issues/906? Would be a nice QOL improvement for helping users debug issues.

**Comment by t0yv0** [comment]
That's a great idea! Yes, very valuable.

**Comment by t0yv0** [comment]
https://github.com/pulumi/pulumi-terraform-bridge/issues/1118 came up as a real QOL improvement opportunity for the providers team; current workarounds include dropping fields entirely in providers such as azure-native to get past the limit on file size.

**Comment by AaronFriel** [comment]
@t0yv0 should #540 be a candidate here as well? It looks like this affects multiple providers.

**Comment by t0yv0** [comment]
Possibly https://github.com/pulumi/pulumi-aws/issues/1655 - highly visible.

**Comment by t0yv0** [comment]
The quarters are changing on us, closing this epic. We've made some progress here. I will open a new epic for Q3 once we have a chance to replan.
