### ISSUE TITLE
[Epic] Unblock provider use of Plugin Framework alongside SDKv2

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-terraform-bridge#981]
Support providers that serve a mix of SDKv2 and Plugin Framework based resources, targeting these three Pulumi providers:

## Requirements

- no unexplained changes in schema
- tests passing on a mix of new and old resources/functions, new tests added as necessary
- functionality for the majority of resources/functions that continue to be implemented against TF SDKv2 upstream continues to use previous production code paths, so we gradually expose new code paths into production

## Work Items ⚙️

These providers combine Plugin Framework and SDKv2 based resources with a gradual transition:

- [x] [CloudFlare](https://github.com/pulumi/pulumi-cloudflare) Status: in prod [v5.1.1](https://github.com/pulumi/pulumi-cloudflare/releases/tag/v5.1.1)
- [x] [Gitlab](https://github.com/pulumi/pulumi-gitlab) Status: in prod [v5.0.0](https://github.com/pulumi/pulumi-gitlab/pull/260)
- [x] [Linode](https://github.com/pulumi/pulumi-linode) Status: in prod [v4.1.0](https://github.com/pulumi/pulumi-linode/releases/tag/v4.1.0)
- [x] [Artifactory](https://github.com/pulumi/pulumi-artifactory) Status: in prod [v3.5.0](https://github.com/pulumi/pulumi-artifactory/releases/tag/v3.5.0)
- [x] [Datadog](https://github.com/pulumi/pulumi-datadog) Status: in prod [v4.18.0](https://github.com/pulumi/pulumi-datadog/releases/tag/v4.18.0)
- [x] [GCP](https://github.com/pulumi/pulumi-gcp) Status: in prod [v6.57.0](https://github.com/pulumi/pulumi-gcp/releases/tag/v6.57.0)
- [ ] [AWS]( https://github.com/pulumi/pulumi-aws) https://github.com/pulumi/pulumi-terraform-bridge/issues/830  WIP https://github.com/pulumi/pulumi-aws/pull/2464 Status: awaiting GCP to deploy to prod first

The following providers are fully based on Plugin Framework:
- [x] [Random](https://github.com/pulumi/pulumi-random) - Status: in prod
- [ ] [TLS](https://github.com/pulumi/pulumi-tls) - Status: awaiting upstream release based on PF

### M0.87
- #946
- #958 
- #972
- #978
- #986
- #989
- #996
- #997
- #1001

### M0.88
- https://github.com/pulumi/pulumi-terraform-bridge/issues/1028
- https://github.com/pulumi/pulumi-terraform-bridge/issues/1032
- https://github.com/pulumi/pulumi-terraform-bridge/issues/1074

### M0.89
- https://github.com/pulumi/pulumi-datadog/issues/276
- https://github.com/pulumi/pulumi-gitlab/issues/273
- https://github.com/pulumi/pulumi-terraform-bridge/pull/1142
- https://github.com/pulumi/pulumi-terraform-bridge/issues/1135

**Comment by t0yv0** [comment]
Some progress, got a build that has strictly additive schema changes and preserves ExtraTypes and is able to deploy resources.

https://github.com/pulumi/pulumi-aws/pull/2464
https://github.com/pulumi/pulumi-terraform-bridge/pull/988

```
name: check
runtime: yaml
description: A minimal Pulumi YAML program
outputs: {}
resources:
  bucket1:
    type: aws:s3:Bucket
  rexpl1:
    type: aws:resourceexplorer/index:Index
    properties:
      type: LOCAL
  cidrcol1:
    type: aws:route53/cidrCollection:CidrCollection
    properties:
     name: collection-2
variables: {}
```

To make this mergeable:

- verify GetMapping 
- verify cmd-line flags to dump MasrhsallableProviderInfo work as before
- verify sdk generation works
- verify tests pass in CI
- do an API simplification pass to tuck away internals from the provider itself
- break apart and check in changes to pulumi-terraform-bridge into the repo to release

**Comment by t0yv0** [comment]
A lot more progress https://github.com/pulumi/pulumi-aws/pull/2464  - this doesn't have any known issues, we're working through CI issues to get a clean passing mark on all tests, and adding some tests specific to PF.

**Comment by t0yv0** [comment]
More progress still, most tests passing except aliased legacy LoadBalancer is failing with, I think @iwahbe is taking this, then we re-test.

```
    error: unrecognized resource type (Check): aws:elasticloadbalancingv2/loadBalancer:LoadBalancer
```

**Comment by t0yv0** [comment]
Per our conversations this issue is now repurposed as an epic encompassing all 3 providers rather than an AWS-specific task. I've added links to known WIP PRs and tracking issues. Feel free to edit. I've less context on what needs to happen for Stage 2, fork removal perhaps? If we want to track it here please populate that section.

**Comment by t0yv0** [comment]
https://github.com/pulumi/pulumi-terraform-bridge/pull/1032 is "almost" ready to review.

    https://github.com/pulumi/home/issues/2849 first cover prod code at ProgramTest level (postmortem follow, scary to edit)
    https://github.com/pulumi/pulumi-terraform-bridge/pull/1086 then merge refactor of prod code
    https://github.com/pulumi/pulumi-terraform-bridge/pull/1065 then rebase, review and merge actual fix

  however 1032 does NOT unblock pulumi-aws, false alarm :/

  https://github.com/pulumi/pulumi-terraform-bridge/issues/1074 is deeper.
     https://github.com/pulumi/pulumi-terraform-bridge/pull/1086 suspect, but have not verified this fixes it

Also want to call out that lack of AutoName support is possible blocker if we move resources that used to rely on AutoName to PF and they lose AutoName that's breaking.

  Support for provider-info level default values and autoname still on track in the iteration.

**Comment by t0yv0** [comment]
Notes from @iwahbe : it's helpful to install autoaliasing before these updates to speed up the process. We're unlocked now and starting to make releases.

**Comment by t0yv0** [comment]
Notes from project sync: AWS has extensive backports; likely first PF release of AWS (+ new version alpha) will not do any of that but simply add net-new PF resources and datasources. Removing backports and using straight PF resources will be left for later, and preferably picked up by pulumi/providers team.

**Comment by t0yv0** [comment]
Possible reasons to do backports sooner: if there's some incompatible changes over the resources in question that coincide with the major version bump; backported resources may defer these breaking changes.

**Comment by t0yv0** [comment]
Closing as complete - https://github.com/pulumi/pulumi-aws/issues/2539 

AWS rollout is happening as 6.0-alpha and tracked in https://github.com/pulumi/pulumi-aws/issues/2539
